// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/loan.proto

package loanpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Loan struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BookName             string   `protobuf:"bytes,3,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	LoanDuration         string   `protobuf:"bytes,4,opt,name=loan_duration,json=loanDuration,proto3" json:"loan_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Loan) Reset()         { *m = Loan{} }
func (m *Loan) String() string { return proto.CompactTextString(m) }
func (*Loan) ProtoMessage()    {}
func (*Loan) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{0}
}

func (m *Loan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Loan.Unmarshal(m, b)
}
func (m *Loan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Loan.Marshal(b, m, deterministic)
}
func (m *Loan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Loan.Merge(m, src)
}
func (m *Loan) XXX_Size() int {
	return xxx_messageInfo_Loan.Size(m)
}
func (m *Loan) XXX_DiscardUnknown() {
	xxx_messageInfo_Loan.DiscardUnknown(m)
}

var xxx_messageInfo_Loan proto.InternalMessageInfo

func (m *Loan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Loan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Loan) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *Loan) GetLoanDuration() string {
	if m != nil {
		return m.LoanDuration
	}
	return ""
}

type CreateLoanReq struct {
	Loan                 *Loan    `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLoanReq) Reset()         { *m = CreateLoanReq{} }
func (m *CreateLoanReq) String() string { return proto.CompactTextString(m) }
func (*CreateLoanReq) ProtoMessage()    {}
func (*CreateLoanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{1}
}

func (m *CreateLoanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoanReq.Unmarshal(m, b)
}
func (m *CreateLoanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoanReq.Marshal(b, m, deterministic)
}
func (m *CreateLoanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoanReq.Merge(m, src)
}
func (m *CreateLoanReq) XXX_Size() int {
	return xxx_messageInfo_CreateLoanReq.Size(m)
}
func (m *CreateLoanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoanReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoanReq proto.InternalMessageInfo

func (m *CreateLoanReq) GetLoan() *Loan {
	if m != nil {
		return m.Loan
	}
	return nil
}

type CreateLoanRes struct {
	Loan                 *Loan    `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLoanRes) Reset()         { *m = CreateLoanRes{} }
func (m *CreateLoanRes) String() string { return proto.CompactTextString(m) }
func (*CreateLoanRes) ProtoMessage()    {}
func (*CreateLoanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{2}
}

func (m *CreateLoanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLoanRes.Unmarshal(m, b)
}
func (m *CreateLoanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLoanRes.Marshal(b, m, deterministic)
}
func (m *CreateLoanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLoanRes.Merge(m, src)
}
func (m *CreateLoanRes) XXX_Size() int {
	return xxx_messageInfo_CreateLoanRes.Size(m)
}
func (m *CreateLoanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLoanRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLoanRes proto.InternalMessageInfo

func (m *CreateLoanRes) GetLoan() *Loan {
	if m != nil {
		return m.Loan
	}
	return nil
}

type UpdateLoanReq struct {
	Loan                 *Loan    `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLoanReq) Reset()         { *m = UpdateLoanReq{} }
func (m *UpdateLoanReq) String() string { return proto.CompactTextString(m) }
func (*UpdateLoanReq) ProtoMessage()    {}
func (*UpdateLoanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{3}
}

func (m *UpdateLoanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLoanReq.Unmarshal(m, b)
}
func (m *UpdateLoanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLoanReq.Marshal(b, m, deterministic)
}
func (m *UpdateLoanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLoanReq.Merge(m, src)
}
func (m *UpdateLoanReq) XXX_Size() int {
	return xxx_messageInfo_UpdateLoanReq.Size(m)
}
func (m *UpdateLoanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLoanReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLoanReq proto.InternalMessageInfo

func (m *UpdateLoanReq) GetLoan() *Loan {
	if m != nil {
		return m.Loan
	}
	return nil
}

type UpdateLoanRes struct {
	Loan                 *Loan    `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLoanRes) Reset()         { *m = UpdateLoanRes{} }
func (m *UpdateLoanRes) String() string { return proto.CompactTextString(m) }
func (*UpdateLoanRes) ProtoMessage()    {}
func (*UpdateLoanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{4}
}

func (m *UpdateLoanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLoanRes.Unmarshal(m, b)
}
func (m *UpdateLoanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLoanRes.Marshal(b, m, deterministic)
}
func (m *UpdateLoanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLoanRes.Merge(m, src)
}
func (m *UpdateLoanRes) XXX_Size() int {
	return xxx_messageInfo_UpdateLoanRes.Size(m)
}
func (m *UpdateLoanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLoanRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLoanRes proto.InternalMessageInfo

func (m *UpdateLoanRes) GetLoan() *Loan {
	if m != nil {
		return m.Loan
	}
	return nil
}

type ReadLoanReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLoanReq) Reset()         { *m = ReadLoanReq{} }
func (m *ReadLoanReq) String() string { return proto.CompactTextString(m) }
func (*ReadLoanReq) ProtoMessage()    {}
func (*ReadLoanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{5}
}

func (m *ReadLoanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLoanReq.Unmarshal(m, b)
}
func (m *ReadLoanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLoanReq.Marshal(b, m, deterministic)
}
func (m *ReadLoanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLoanReq.Merge(m, src)
}
func (m *ReadLoanReq) XXX_Size() int {
	return xxx_messageInfo_ReadLoanReq.Size(m)
}
func (m *ReadLoanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLoanReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLoanReq proto.InternalMessageInfo

func (m *ReadLoanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadLoanRes struct {
	Loan                 *Loan    `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadLoanRes) Reset()         { *m = ReadLoanRes{} }
func (m *ReadLoanRes) String() string { return proto.CompactTextString(m) }
func (*ReadLoanRes) ProtoMessage()    {}
func (*ReadLoanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{6}
}

func (m *ReadLoanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadLoanRes.Unmarshal(m, b)
}
func (m *ReadLoanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadLoanRes.Marshal(b, m, deterministic)
}
func (m *ReadLoanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadLoanRes.Merge(m, src)
}
func (m *ReadLoanRes) XXX_Size() int {
	return xxx_messageInfo_ReadLoanRes.Size(m)
}
func (m *ReadLoanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadLoanRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadLoanRes proto.InternalMessageInfo

func (m *ReadLoanRes) GetLoan() *Loan {
	if m != nil {
		return m.Loan
	}
	return nil
}

type DeleteLoanReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLoanReq) Reset()         { *m = DeleteLoanReq{} }
func (m *DeleteLoanReq) String() string { return proto.CompactTextString(m) }
func (*DeleteLoanReq) ProtoMessage()    {}
func (*DeleteLoanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{7}
}

func (m *DeleteLoanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLoanReq.Unmarshal(m, b)
}
func (m *DeleteLoanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLoanReq.Marshal(b, m, deterministic)
}
func (m *DeleteLoanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLoanReq.Merge(m, src)
}
func (m *DeleteLoanReq) XXX_Size() int {
	return xxx_messageInfo_DeleteLoanReq.Size(m)
}
func (m *DeleteLoanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLoanReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLoanReq proto.InternalMessageInfo

func (m *DeleteLoanReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteLoanRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLoanRes) Reset()         { *m = DeleteLoanRes{} }
func (m *DeleteLoanRes) String() string { return proto.CompactTextString(m) }
func (*DeleteLoanRes) ProtoMessage()    {}
func (*DeleteLoanRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e6f680697400d9a, []int{8}
}

func (m *DeleteLoanRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLoanRes.Unmarshal(m, b)
}
func (m *DeleteLoanRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLoanRes.Marshal(b, m, deterministic)
}
func (m *DeleteLoanRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLoanRes.Merge(m, src)
}
func (m *DeleteLoanRes) XXX_Size() int {
	return xxx_messageInfo_DeleteLoanRes.Size(m)
}
func (m *DeleteLoanRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLoanRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLoanRes proto.InternalMessageInfo

func (m *DeleteLoanRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Loan)(nil), "proto.Loan")
	proto.RegisterType((*CreateLoanReq)(nil), "proto.CreateLoanReq")
	proto.RegisterType((*CreateLoanRes)(nil), "proto.CreateLoanRes")
	proto.RegisterType((*UpdateLoanReq)(nil), "proto.UpdateLoanReq")
	proto.RegisterType((*UpdateLoanRes)(nil), "proto.UpdateLoanRes")
	proto.RegisterType((*ReadLoanReq)(nil), "proto.ReadLoanReq")
	proto.RegisterType((*ReadLoanRes)(nil), "proto.ReadLoanRes")
	proto.RegisterType((*DeleteLoanReq)(nil), "proto.DeleteLoanReq")
	proto.RegisterType((*DeleteLoanRes)(nil), "proto.DeleteLoanRes")
}

func init() { proto.RegisterFile("proto/loan.proto", fileDescriptor_3e6f680697400d9a) }

var fileDescriptor_3e6f680697400d9a = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x3d, 0x4f, 0xb4, 0x40,
	0x10, 0x0e, 0xbc, 0xbc, 0xca, 0x0d, 0xc7, 0xc5, 0x4c, 0x2c, 0x08, 0xc6, 0x9c, 0xc1, 0x46, 0x1b,
	0x34, 0xd8, 0x98, 0xd8, 0xe9, 0x95, 0xc6, 0x02, 0x63, 0x63, 0x73, 0x59, 0xd8, 0x2d, 0x88, 0xc8,
	0x22, 0xcb, 0xf9, 0xb7, 0xfd, 0x0b, 0x66, 0x47, 0x38, 0x3e, 0xa4, 0xc0, 0x0a, 0xf6, 0xf9, 0x98,
	0x67, 0xe7, 0x59, 0x38, 0x2a, 0x2b, 0x59, 0xcb, 0xab, 0x5c, 0xb2, 0x22, 0xa4, 0x5f, 0xfc, 0x4f,
	0x9f, 0x20, 0x07, 0xeb, 0x51, 0xb2, 0x02, 0x57, 0x60, 0x66, 0xdc, 0x33, 0xce, 0x8c, 0x8b, 0x45,
	0x6c, 0x66, 0x1c, 0x11, 0xac, 0x82, 0xbd, 0x0b, 0xcf, 0x24, 0x84, 0xfe, 0xf1, 0x04, 0x16, 0x89,
	0x94, 0x6f, 0x5b, 0x22, 0xfe, 0x11, 0x61, 0x6b, 0xe0, 0x49, 0x93, 0xe7, 0xe0, 0xea, 0xe9, 0x5b,
	0xbe, 0xab, 0x58, 0x9d, 0xc9, 0xc2, 0xb3, 0x48, 0xb0, 0xd4, 0xe0, 0xa6, 0xc1, 0x82, 0x6b, 0x70,
	0x1f, 0x2a, 0xc1, 0x6a, 0xa1, 0x33, 0x63, 0xf1, 0x81, 0x6b, 0xb0, 0xb4, 0x80, 0x82, 0x9d, 0xc8,
	0xf9, 0xb9, 0x5b, 0x48, 0x2c, 0x11, 0x63, 0x87, 0x9a, 0xe5, 0x78, 0x29, 0xf9, 0x1f, 0x33, 0xfa,
	0x8e, 0x19, 0x19, 0xa7, 0xe0, 0xc4, 0x82, 0xf1, 0x36, 0x61, 0x54, 0x5e, 0x10, 0xf6, 0xe9, 0x19,
	0xe3, 0xd6, 0xe0, 0x6e, 0x44, 0x2e, 0xba, 0x2b, 0x8f, 0x07, 0x5e, 0x0e, 0x05, 0x0a, 0x3d, 0x38,
	0x54, 0xbb, 0x34, 0x15, 0x4a, 0x91, 0xca, 0x8e, 0xdb, 0x63, 0xf4, 0x65, 0x80, 0xa3, 0x55, 0xcf,
	0xa2, 0xfa, 0xcc, 0x52, 0x81, 0xb7, 0x00, 0x5d, 0x81, 0x78, 0xdc, 0x84, 0x0f, 0x5e, 0xc1, 0x9f,
	0x42, 0x15, 0x46, 0x60, 0xb7, 0x5b, 0x20, 0x36, 0x8a, 0xde, 0xd6, 0xfe, 0x6f, 0x4c, 0xe9, 0xb4,
	0xae, 0xca, 0x7d, 0xda, 0xe0, 0x3d, 0xfc, 0x29, 0x94, 0x9c, 0xdd, 0x8a, 0x7b, 0xe7, 0xa0, 0x16,
	0x7f, 0x0a, 0x55, 0xf7, 0xab, 0xd7, 0x25, 0xc1, 0x77, 0xba, 0xcb, 0x32, 0x49, 0x0e, 0xe8, 0x74,
	0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x98, 0xe2, 0x6f, 0x6c, 0xf4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoanServiceClient interface {
	CreateLoan(ctx context.Context, in *CreateLoanReq, opts ...grpc.CallOption) (*CreateLoanRes, error)
	ReadLoan(ctx context.Context, in *ReadLoanReq, opts ...grpc.CallOption) (*ReadLoanRes, error)
	UpdateLoan(ctx context.Context, in *UpdateLoanReq, opts ...grpc.CallOption) (*UpdateLoanRes, error)
	DeleteLoan(ctx context.Context, in *DeleteLoanReq, opts ...grpc.CallOption) (*DeleteLoanRes, error)
}

type loanServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoanServiceClient(cc *grpc.ClientConn) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) CreateLoan(ctx context.Context, in *CreateLoanReq, opts ...grpc.CallOption) (*CreateLoanRes, error) {
	out := new(CreateLoanRes)
	err := c.cc.Invoke(ctx, "/proto.LoanService/CreateLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ReadLoan(ctx context.Context, in *ReadLoanReq, opts ...grpc.CallOption) (*ReadLoanRes, error) {
	out := new(ReadLoanRes)
	err := c.cc.Invoke(ctx, "/proto.LoanService/ReadLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) UpdateLoan(ctx context.Context, in *UpdateLoanReq, opts ...grpc.CallOption) (*UpdateLoanRes, error) {
	out := new(UpdateLoanRes)
	err := c.cc.Invoke(ctx, "/proto.LoanService/UpdateLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) DeleteLoan(ctx context.Context, in *DeleteLoanReq, opts ...grpc.CallOption) (*DeleteLoanRes, error) {
	out := new(DeleteLoanRes)
	err := c.cc.Invoke(ctx, "/proto.LoanService/DeleteLoan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
type LoanServiceServer interface {
	CreateLoan(context.Context, *CreateLoanReq) (*CreateLoanRes, error)
	ReadLoan(context.Context, *ReadLoanReq) (*ReadLoanRes, error)
	UpdateLoan(context.Context, *UpdateLoanReq) (*UpdateLoanRes, error)
	DeleteLoan(context.Context, *DeleteLoanReq) (*DeleteLoanRes, error)
}

func RegisterLoanServiceServer(s *grpc.Server, srv LoanServiceServer) {
	s.RegisterService(&_LoanService_serviceDesc, srv)
}

func _LoanService_CreateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).CreateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoanService/CreateLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).CreateLoan(ctx, req.(*CreateLoanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ReadLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLoanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ReadLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoanService/ReadLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ReadLoan(ctx, req.(*ReadLoanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_UpdateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).UpdateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoanService/UpdateLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).UpdateLoan(ctx, req.(*UpdateLoanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_DeleteLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).DeleteLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LoanService/DeleteLoan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).DeleteLoan(ctx, req.(*DeleteLoanReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoanService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoan",
			Handler:    _LoanService_CreateLoan_Handler,
		},
		{
			MethodName: "ReadLoan",
			Handler:    _LoanService_ReadLoan_Handler,
		},
		{
			MethodName: "UpdateLoan",
			Handler:    _LoanService_UpdateLoan_Handler,
		},
		{
			MethodName: "DeleteLoan",
			Handler:    _LoanService_DeleteLoan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/loan.proto",
}
