// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/book.proto

package bookpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateBookReq struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookReq) Reset()         { *m = CreateBookReq{} }
func (m *CreateBookReq) String() string { return proto.CompactTextString(m) }
func (*CreateBookReq) ProtoMessage()    {}
func (*CreateBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{1}
}

func (m *CreateBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookReq.Unmarshal(m, b)
}
func (m *CreateBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookReq.Marshal(b, m, deterministic)
}
func (m *CreateBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookReq.Merge(m, src)
}
func (m *CreateBookReq) XXX_Size() int {
	return xxx_messageInfo_CreateBookReq.Size(m)
}
func (m *CreateBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookReq proto.InternalMessageInfo

func (m *CreateBookReq) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type CreateBookRes struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRes) Reset()         { *m = CreateBookRes{} }
func (m *CreateBookRes) String() string { return proto.CompactTextString(m) }
func (*CreateBookRes) ProtoMessage()    {}
func (*CreateBookRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{2}
}

func (m *CreateBookRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRes.Unmarshal(m, b)
}
func (m *CreateBookRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRes.Marshal(b, m, deterministic)
}
func (m *CreateBookRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRes.Merge(m, src)
}
func (m *CreateBookRes) XXX_Size() int {
	return xxx_messageInfo_CreateBookRes.Size(m)
}
func (m *CreateBookRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRes proto.InternalMessageInfo

func (m *CreateBookRes) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookReq struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookReq) Reset()         { *m = UpdateBookReq{} }
func (m *UpdateBookReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBookReq) ProtoMessage()    {}
func (*UpdateBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{3}
}

func (m *UpdateBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookReq.Unmarshal(m, b)
}
func (m *UpdateBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookReq.Marshal(b, m, deterministic)
}
func (m *UpdateBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookReq.Merge(m, src)
}
func (m *UpdateBookReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBookReq.Size(m)
}
func (m *UpdateBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookReq proto.InternalMessageInfo

func (m *UpdateBookReq) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type UpdateBookRes struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookRes) Reset()         { *m = UpdateBookRes{} }
func (m *UpdateBookRes) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRes) ProtoMessage()    {}
func (*UpdateBookRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{4}
}

func (m *UpdateBookRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRes.Unmarshal(m, b)
}
func (m *UpdateBookRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRes.Marshal(b, m, deterministic)
}
func (m *UpdateBookRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRes.Merge(m, src)
}
func (m *UpdateBookRes) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRes.Size(m)
}
func (m *UpdateBookRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRes proto.InternalMessageInfo

func (m *UpdateBookRes) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type ReadBookReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBookReq) Reset()         { *m = ReadBookReq{} }
func (m *ReadBookReq) String() string { return proto.CompactTextString(m) }
func (*ReadBookReq) ProtoMessage()    {}
func (*ReadBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{5}
}

func (m *ReadBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBookReq.Unmarshal(m, b)
}
func (m *ReadBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBookReq.Marshal(b, m, deterministic)
}
func (m *ReadBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBookReq.Merge(m, src)
}
func (m *ReadBookReq) XXX_Size() int {
	return xxx_messageInfo_ReadBookReq.Size(m)
}
func (m *ReadBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBookReq proto.InternalMessageInfo

func (m *ReadBookReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadBookRes struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBookRes) Reset()         { *m = ReadBookRes{} }
func (m *ReadBookRes) String() string { return proto.CompactTextString(m) }
func (*ReadBookRes) ProtoMessage()    {}
func (*ReadBookRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{6}
}

func (m *ReadBookRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBookRes.Unmarshal(m, b)
}
func (m *ReadBookRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBookRes.Marshal(b, m, deterministic)
}
func (m *ReadBookRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBookRes.Merge(m, src)
}
func (m *ReadBookRes) XXX_Size() int {
	return xxx_messageInfo_ReadBookRes.Size(m)
}
func (m *ReadBookRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBookRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBookRes proto.InternalMessageInfo

func (m *ReadBookRes) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type DeleteBookReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookReq) Reset()         { *m = DeleteBookReq{} }
func (m *DeleteBookReq) String() string { return proto.CompactTextString(m) }
func (*DeleteBookReq) ProtoMessage()    {}
func (*DeleteBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{7}
}

func (m *DeleteBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookReq.Unmarshal(m, b)
}
func (m *DeleteBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookReq.Marshal(b, m, deterministic)
}
func (m *DeleteBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookReq.Merge(m, src)
}
func (m *DeleteBookReq) XXX_Size() int {
	return xxx_messageInfo_DeleteBookReq.Size(m)
}
func (m *DeleteBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookReq proto.InternalMessageInfo

func (m *DeleteBookReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBookRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRes) Reset()         { *m = DeleteBookRes{} }
func (m *DeleteBookRes) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRes) ProtoMessage()    {}
func (*DeleteBookRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_eff6d7530e9d9699, []int{8}
}

func (m *DeleteBookRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRes.Unmarshal(m, b)
}
func (m *DeleteBookRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRes.Marshal(b, m, deterministic)
}
func (m *DeleteBookRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRes.Merge(m, src)
}
func (m *DeleteBookRes) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRes.Size(m)
}
func (m *DeleteBookRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRes proto.InternalMessageInfo

func (m *DeleteBookRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Book)(nil), "proto.Book")
	proto.RegisterType((*CreateBookReq)(nil), "proto.CreateBookReq")
	proto.RegisterType((*CreateBookRes)(nil), "proto.CreateBookRes")
	proto.RegisterType((*UpdateBookReq)(nil), "proto.UpdateBookReq")
	proto.RegisterType((*UpdateBookRes)(nil), "proto.UpdateBookRes")
	proto.RegisterType((*ReadBookReq)(nil), "proto.ReadBookReq")
	proto.RegisterType((*ReadBookRes)(nil), "proto.ReadBookRes")
	proto.RegisterType((*DeleteBookReq)(nil), "proto.DeleteBookReq")
	proto.RegisterType((*DeleteBookRes)(nil), "proto.DeleteBookRes")
}

func init() { proto.RegisterFile("proto/book.proto", fileDescriptor_eff6d7530e9d9699) }

var fileDescriptor_eff6d7530e9d9699 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x0d, 0x48, 0x6b, 0x1d, 0x6c, 0x63, 0x26, 0x8d, 0x21, 0x24, 0xa6, 0x0d, 0x27, 0xbd, 0xa0,
	0xc1, 0x8b, 0x89, 0xb7, 0xea, 0x2f, 0xc0, 0x78, 0xf1, 0xc6, 0xc7, 0x18, 0x37, 0x6d, 0x5c, 0x64,
	0xb7, 0xfe, 0x6d, 0xff, 0x82, 0xd9, 0x29, 0x94, 0x0f, 0x39, 0xe0, 0x09, 0xe6, 0xcd, 0x7b, 0xfb,
	0x66, 0xde, 0xc0, 0x45, 0x51, 0x4a, 0x2d, 0x6f, 0x53, 0x29, 0xb7, 0x21, 0xff, 0xe2, 0x84, 0x3f,
	0xc1, 0x3b, 0x38, 0x1b, 0x29, 0xb7, 0xb8, 0x00, 0x5b, 0xe4, 0x9e, 0xb5, 0xb6, 0xae, 0xcf, 0x62,
	0x5b, 0xe4, 0x78, 0x09, 0xd3, 0x64, 0xaf, 0x3f, 0x64, 0xe9, 0xd9, 0x8c, 0x55, 0x15, 0x2e, 0x61,
	0xa2, 0x85, 0xde, 0x91, 0x77, 0xc2, 0xf0, 0xa1, 0xc0, 0x35, 0xb8, 0x39, 0xa9, 0xac, 0x14, 0x85,
	0x16, 0xf2, 0xd3, 0x73, 0xb8, 0xd7, 0x86, 0x82, 0x3b, 0x98, 0x3f, 0x95, 0x94, 0x68, 0x32, 0x6e,
	0x31, 0x7d, 0xe1, 0x0a, 0x1c, 0x33, 0x0d, 0x5b, 0xba, 0x91, 0x7b, 0x98, 0x2a, 0xe4, 0x2e, 0x37,
	0xfa, 0x0a, 0x35, 0x4a, 0xf1, 0x5a, 0xe4, 0xff, 0xf4, 0x68, 0x2b, 0x46, 0x78, 0x5c, 0x81, 0x1b,
	0x53, 0x92, 0xd7, 0x0e, 0xbd, 0xd8, 0x82, 0xb0, 0xdd, 0x1e, 0xf1, 0xdc, 0x0a, 0xe6, 0xcf, 0xb4,
	0xa3, 0x66, 0xe4, 0xfe, 0x83, 0x37, 0x5d, 0x82, 0x42, 0x0f, 0x4e, 0xd5, 0x3e, 0xcb, 0x48, 0x29,
	0x66, 0xcd, 0xe2, 0xba, 0x8c, 0x7e, 0x2c, 0x70, 0x0d, 0xeb, 0x85, 0xca, 0x6f, 0x91, 0x11, 0x3e,
	0x00, 0x34, 0x01, 0xe2, 0xb2, 0x32, 0xef, 0x5c, 0xc1, 0x1f, 0x42, 0x15, 0x46, 0x30, 0xab, 0xb7,
	0x40, 0xac, 0x18, 0xad, 0xad, 0xfd, 0xbf, 0x98, 0x32, 0x6e, 0x4d, 0x94, 0x47, 0xb7, 0xce, 0x3d,
	0xfc, 0x21, 0x94, 0x95, 0xcd, 0x8a, 0x47, 0x65, 0x27, 0x16, 0x7f, 0x08, 0x55, 0x9b, 0xc5, 0xdb,
	0x39, 0xc3, 0x8f, 0x26, 0xcb, 0x22, 0x4d, 0xa7, 0x5c, 0xdd, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x33, 0x53, 0x7d, 0x25, 0xee, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	CreateBook(ctx context.Context, in *CreateBookReq, opts ...grpc.CallOption) (*CreateBookRes, error)
	ReadBook(ctx context.Context, in *ReadBookReq, opts ...grpc.CallOption) (*ReadBookRes, error)
	UpdateBook(ctx context.Context, in *UpdateBookReq, opts ...grpc.CallOption) (*UpdateBookRes, error)
	DeleteBook(ctx context.Context, in *DeleteBookReq, opts ...grpc.CallOption) (*DeleteBookRes, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) CreateBook(ctx context.Context, in *CreateBookReq, opts ...grpc.CallOption) (*CreateBookRes, error) {
	out := new(CreateBookRes)
	err := c.cc.Invoke(ctx, "/proto.BookService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) ReadBook(ctx context.Context, in *ReadBookReq, opts ...grpc.CallOption) (*ReadBookRes, error) {
	out := new(ReadBookRes)
	err := c.cc.Invoke(ctx, "/proto.BookService/ReadBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) UpdateBook(ctx context.Context, in *UpdateBookReq, opts ...grpc.CallOption) (*UpdateBookRes, error) {
	out := new(UpdateBookRes)
	err := c.cc.Invoke(ctx, "/proto.BookService/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBook(ctx context.Context, in *DeleteBookReq, opts ...grpc.CallOption) (*DeleteBookRes, error) {
	out := new(DeleteBookRes)
	err := c.cc.Invoke(ctx, "/proto.BookService/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	CreateBook(context.Context, *CreateBookReq) (*CreateBookRes, error)
	ReadBook(context.Context, *ReadBookReq) (*ReadBookRes, error)
	UpdateBook(context.Context, *UpdateBookReq) (*UpdateBookRes, error)
	DeleteBook(context.Context, *DeleteBookReq) (*DeleteBookRes, error)
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).CreateBook(ctx, req.(*CreateBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_ReadBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).ReadBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookService/ReadBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).ReadBook(ctx, req.(*ReadBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookService/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).UpdateBook(ctx, req.(*UpdateBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookService/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBook(ctx, req.(*DeleteBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _BookService_CreateBook_Handler,
		},
		{
			MethodName: "ReadBook",
			Handler:    _BookService_ReadBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _BookService_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookService_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/book.proto",
}
